package main.domini;

import java.awt.*;
import java.io.*;
import java.lang.*;
import java.nio.*;
import java.io.FileInputStream;
import java.util.*;
import java.util.Scanner;
import java.lang.Object;

public class JPEG_Driver {

	public JPEG_Driver() {}

	public static void main(String[] args) throws IOException {

		System.out.println("");
		System.out.println("####################################################");
		System.out.println("# JPEG_Driver #build 3.4 - last revision: 10.11.19 #");
		System.out.println("####################################################");
		System.out.println("");

		System.out.println("Please, choose an option:");
		System.out.println("1. Compress");
		System.out.println("2. Decompress");
		System.out.println("3. Compress & Decompress");
		System.out.print("I choose: ");

		Scanner in = new Scanner(System.in);
		int n = in.nextInt();

		if (n > 3 || n < 1) {
			System.out.println("");
			System.out.println("Number must be between 1 and 3");
			System.out.println("");
			System.exit(0);
		}

		System.out.println("");
		System.out.println("Please, provide the PATH of the files that you want to play with:");
		System.out.println("IMPORTANT:");
		System.out.println("Note that for Compress, the input must be a .ppm file of type P6");
		System.out.println("For Decompress the output must be also .ppm");
		System.out.println("A compressed file can have any extention, but the content must have been generated by this program");
		System.out.println("");

		System.out.println("Input name:");
        String inputString = in.next();

		System.out.println("");

		System.out.println("Output name:");
		String outputString = in.next();

		File file = new File(inputString);
        byte[] b = new byte[(int) file.length()];
        FileInputStream fis = new FileInputStream(file);
        fis.read(b);
        fis.close();

        Object[] outputBytes = new Object[2];


        System.out.println("");
        System.out.println("Do you want a verbose output?");
		System.out.print("(y/n):");
		System.out.println("");

		char c = in.next().charAt(0);

		JPEG jpeg = new JPEG();

		if (c == 'y')
			jpeg = new JPEG(true);

		else if (c != 'n') {
			System.out.println("");
			System.out.println("Char must be y or n");
			System.out.println("");
			System.exit(0);
		}

		switch (n) {
			
			case 1 :
				// Compress
				outputBytes = jpeg.comprimir(b);
				break;

			case 2 :
				// Decompress
				outputBytes = jpeg.descomprimir(b);
				break;

			case 3 :
				// Compress & Decompress
				Object[] a = jpeg.comprimir(b);
				outputBytes = jpeg.descomprimir((byte[]) a[0]);
				outputBytes[1] = (long) outputBytes[1] + (long) a[1];
				break;
		}

		System.out.println("");
		System.out.println("Done!");
		System.out.print("Total time: ");
		System.out.print(outputBytes[1]);
		System.out.println(" milliseconds");
		System.out.println("");

        File file2 = new File(outputString);
        OutputStream os = new FileOutputStream(file2);
        os.write((byte[]) outputBytes[0]);

        System.out.println("Your file has been saved at " + outputString);
        System.out.println("");
	}
}